# Generated by Django 3.2.8 on 2021-12-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='people',
            new_name='peop',
        ),
    ]
