# Generated by Django 3.2.8 on 2021-12-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0003_auto_20211202_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=30, null=True)),
                ('pri', models.IntegerField(max_length=30, null=True)),
            ],
        ),
    ]
