# Generated by Django 3.2.8 on 2021-12-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0004_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pri',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='pro',
            new_name='product',
        ),
    ]
