# Generated by Django 3.2.8 on 2022-01-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0005_auto_20211210_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='custdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
